services:
  lkserver:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - LIVEKIT_API_KEY=${LK_API_KEY}
      - LIVEKIT_API_SECRET=${LK_API_SECRET}
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    command: --config /etc/livekit.yaml --node-ip 127.0.0.1

turn:
  image: coturn/coturn
  restart: unless-stopped
  command:
    [
      "turnserver",
      "-n",
      "--fingerprint",
      "--lt-cred-mech",
      "--realm=livekit.local",
      "--user=turnuser:turnpass",
      "--listening-port=3478",
      "--listening-ip=0.0.0.0",
      "--relay-ip=0.0.0.0",
      "--min-port=10000",
      "--max-port=20000",
    ]
  ports:
    - "3478:3478"
    - "10000-20000:10000-20000/udp"
  networks:
    - default
