services:
  redis:
    build: ../../services/redis
    platform: linux/arm64
    command: --requirepass ${REDIS_PASSWORD:-buddytalk}
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - default
